NODE_ENV=development

HOST=localhost
PORT=3001
APP_LANGUAGE=vi
FALLBACK_LANGUAGE=vi
TZ=Asia/Ho_Chi_Minh
REQUEST_BODY_LIMIT=50mb
ENABLE_CRON=false

# Database
DB_HOST=localhost
DB_PORT=5432
DB_USERNAME=postgres
DB_PASSWORD=
DB_DATABASE=team-task-db1-v1

# JWT
JWT_SECRET=your-jwt-secret
JWT_EXPIRES_IN=1d
JWT_REFRESH_SECRET=your-jwt-refresh-secret
JWT_REFRESH_EXPIRES_IN=7d

# Redis
REDIS_HOST=localhost
REDIS_PORT=6379
REDIS_PASSWORD=
REDIS_PREFIX=

# Minio
MINIO_ENDPOINT=localhost
MINIO_PORT=9000
MINIO_CONSOLE_PORT=9001
MINIO_ROOT_USER=
MINIO_ROOT_PASSWORD=